### ISSUE TITLE
Underlining kanji in sentence

### ISSUE THREAD

**Issue by donkuri** [Michael-128/clean-anki-cards#1]
Hi, great note type!
Have you considered using another way to target the word in the sentence other than underlining? I like your note but I feel like it's making kanji harder to read. I usually bold the word instead, usually with some different color using `b{color: #something}`. Have you considered doing something like that? Not an issue per se, just thought I'd give you my thoughts. Great work!

**Comment by Michael-128** [comment]
Thanks for the suggestion! I've decided to underline the highlighted word, because it wasn't visible enough for my liking after making it bolder. I didn't think about changing the color, but I will definitely try that out.

You can replace the respective sections of the existing CSS with the following code to remove underline and make the highlighted word bolder instead. You can also modify the color.  Feel free to ask any questions!
```css
.card #sentence #word-highlight {
	color: black;
	font-weight: bold;
}

/* Color of the highlighted word for the dark mode */
.card.nightMode #sentence #word-highlight {
	color: white;
}
```
